# Generated by Django 4.0.6 on 2022-07-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(to='catalogue.genre'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='award',
            field=models.CharField(blank=True, help_text='Which award did this film win?', max_length=40, null=True),
        ),
        migrations.RemoveField(
            model_name='film',
            name='awards',
        ),
        migrations.AddField(
            model_name='film',
            name='awards',
            field=models.ManyToManyField(to='catalogue.awards'),
        ),
        migrations.RemoveField(
            model_name='film',
            name='casting',
        ),
        migrations.AddField(
            model_name='film',
            name='casting',
            field=models.ManyToManyField(to='catalogue.casting'),
        ),
    ]
